### PR TITLE
Zuo/np convert

### PR DESCRIPTION
**Pull request by zuoshifan**
Improve conversion between distributed array and numpy array.

### CODE REVIEW

**Comment by jrs65** [comment]
Looks good to me. 

A few suggested changes:
 - Rather than having a default grid_shape of [1, nprocesses], it might be more useful to try and split into a roughly square distribution which I think is usually faster on the sort of routines we are intersted in (eigenvalues etc).
 - I'd prefer not to have the default grid shape actually in the argument (instead have the value be None, and test for it). This is because the default arguments are only evaluated once, if for some reason the size of COMM_WORLD changes (if a process is dynamically added), then it will not get the new size.
 - Also, maybe up the default block_shape to [32, 32] or thereabouts. I think these intermediate sizes  are fastest with most scalapack distributions.

Thanks for all your work.

**Comment by poulson** [comment]
Yes, near-square process grids and a blocksize of 32 is the "right" default.

**Comment by zuoshifan** [comment]
Thank you for suggestions.

**Comment by jrs65** [comment]
Thanks for the advice Jack. Very useful to get a more expert view.

This has prompted me that I completely lost track of your email of a while ago, and I never replied. Profuse apologies!!! I'll get to that one pronto.

**Pull request merged**
